version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: skaxis
      MYSQL_USER: skaxis
      MYSQL_PASSWORD: skaxispassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

  fastapi:
    image: ${DOCKER_USERNAME}/skaxis-ai:latest
    container_name: fastapi
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    volumes:
      - shared_output:/shared-output
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=mysql://skaxis:skaxispassword@mysql:3306/skaxis
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    restart: unless-stopped

  springboot:
    image: ${DOCKER_USERNAME}/skaxis-server:latest
    container_name: springboot
    ports:
      - "${SPRINGBOOT_PORT:-8080}:8080"
    volumes:
      - shared_output:/shared-output
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/skaxis?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=skaxis
      - SPRING_DATASOURCE_PASSWORD=skaxispassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FASTAPI_URL=http://fastapi:8000/api/v1
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
      - fastapi
    networks:
      - app-network
    restart: unless-stopped

  client:
    image: ${DOCKER_USERNAME}/skaxis-client:latest
    container_name: client
    ports:
      - "${CLIENT_PORT:-80}:80"
    environment:
      - API_URL=/api
      - WS_URL=/ws
    depends_on:
      - springboot
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  shared_output:

networks:
  app-network:
    driver: bridge