version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:latest
    container_name: redis-prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data-prod:/data

  springboot:
    image: wochae/sk-axis-server:latest # Docker Hub 이미지 경로
    container_name: springboot-prod
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

volumes:
  mysql-data-prod:
  redis-data-prod: