openapi: 3.0.1
info:
  title: SK AXIS AI Interview Internal API
  description: Spring Boot ↔ FastAPI 연동 전용 API 명세서 (다대다 질문 조회 포함 + WebSocket 확장)
  version: "1.0.0"

servers:
  - url: http://sk-axis-springboot:8080/api/v1

tags:
  - name: Internal
    description: 내부 시스템 연동 API (FastAPI → Spring Boot)

paths:
  /internal/interviewees/questions:
    post:
      tags: [Internal]
      summary: 다중 지원자 질문 5개 조회 (FastAPI → Spring Boot)
      description: |
        면접 시작 시 FastAPI가 여러 명의 지원자 ID를 Spring Boot로 전달하여,
        각 지원자별 질문 5개(공통 3 + 개별 2)를 한번에 요청하는 내부 API입니다.
      operationId: getMultipleIntervieweeQuestions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                interviewee_ids:
                  type: array
                  items:
                    type: integer
                  example: [101, 102, 103]
      responses:
        '200':
          description: 각 지원자별 질문 반환 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  questions_per_interviewee:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        $ref: '#/components/schemas/Question'
                example:
                  questions_per_interviewee:
                    "101":
                      - question_id: 1
                        type: 공통질문
                        content: "본인의 장점을 말씀해 주세요."
                      - question_id: 2
                        type: 공통질문
                        content: "팀워크 경험 중 기억에 남는 일은?"
                      - question_id: 3
                        type: 공통질문
                        content: "협업 시 중요하게 생각하는 점은?"
                      - question_id: 4
                        type: 개별질문
                        content: "자기소개서에 언급한 프로젝트를 설명해 주세요."
                      - question_id: 5
                        type: 개별질문
                        content: "지원 동기를 말씀해 주세요."
                    "102":
                      - question_id: 6
                        type: 공통질문
                        content: "본인의 장점을 말씀해 주세요."
                      - question_id: 7
                        type: 공통질문
                        content: "팀워크 경험 중 기억에 남는 일은?"
                      - question_id: 8
                        type: 공통질문
                        content: "협업 시 중요하게 생각하는 점은?"
                      - question_id: 9
                        type: 개별질문
                        content: "대외활동 중 기억에 남는 경험은?"
                      - question_id: 10
                        type: 개별질문
                        content: "이 회사에 지원한 이유는?"
        '404':
          description: 일부 또는 전체 지원자의 질문을 찾을 수 없음

components:
  schemas:
    Question:
      type: object
      properties:
        question_id:
          type: integer
        type:
          type: string
          enum: [공통질문, 개별질문]
        content:
          type: string
