name: Deploy Server Service

on:
  push:
    branches:
      - back
      - 'back/**'
      - main
    paths:
      - 'server/**'

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Server image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest \
            --push ./server/spring

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ec2-user/SK-AXIS
            docker pull ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest
            docker-compose -f docker-compose.prod.yml down springboot || true
            docker-compose -f docker-compose.prod.yml up -d springboot
            docker-compose -f docker-compose.prod.yml ps
            docker image prune -f
            echo "=== 업데이트 완료! ==="
            docker-compose -f docker-compose.dev.yml ps
