name: Deploy Server Service

on:
  push:
    branches:
      - '**'  # 모든 브랜치에 대해 CI는 실행 가능하게
    paths:
      - 'server/**'

jobs:
  ci:
    name: Build & Test Only (no deploy)
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'  # main이 아닐 때만 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build only
        run: |
          echo "🧪 This is a CI check only. No deploy will happen."
          docker build ./server/spring

  cd:
    name: Build & Deploy on main
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # main일 때만 배포
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Server image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest \
            --push ./server/spring

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ec2-user/SK-AXIS
            docker pull ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest
            docker-compose -f docker-compose.dev.yml down springboot || true
            docker-compose -f docker-compose.dev.yml up -d springboot
            docker image prune -f
            docker-compose -f docker-compose.dev.yml ps
