name: Deploy AI and Client Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'ai/**'
      - 'client/**'

jobs:
  build-and-deploy-ai:
    name: Build & Deploy AI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push AI image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/skaxis-ai:latest \
            --push ./ai

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ec2-user/SK-AXIS
            docker pull ${{ secrets.DOCKER_USERNAME }}/skaxis-ai:latest
            docker-compose -f docker-compose.prod.yml down fastapi || true
            docker-compose -f docker-compose.prod.yml up -d fastapi
            docker image prune -f

  build-and-deploy-client:
    name: Build & Deploy Client
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Client image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/skaxis-client:latest \
            --push ./client

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ec2-user/SK-AXIS
            docker pull ${{ secrets.DOCKER_USERNAME }}/skaxis-client:latest
            docker-compose -f docker-compose.prod.yml down client || true
            docker-compose -f docker-compose.prod.yml up -d client
            docker image prune -f
