name: Deploy Server Service

on:
  push:
    branches:
      - back
    paths:
      - 'server/**'

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Server image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest \
            --push ./server/spring

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "=== SK-AXIS 업데이트 시작 ==="
            docker pull --platform linux/amd64 ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest
            docker-compose down springboot || true
            docker-compose up -d springboot
            docker image prune -f
            echo "=== 업데이트 완료! ==="
            docker-compose ps
