# name: Deploy Server Service

# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'server/**'
#   pull_request:
#     branches: [ main ]
#     paths:
#       - 'server/**'

# jobs:
#   build-and-deploy-server:
#     runs-on: ubuntu-latest
#     environment: deploy
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#     - name: Log in to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#     - name: Build and push Server image
#       run: |
#         docker build -t ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest ./server/spring
#         docker push ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest
#     - name: Deploy Server to EC2
#       uses: appleboy/ssh-action@v1.0.0
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ec2-user
#         key: ${{ secrets.EC2_SSH_KEY }}
#         port: ${{ secrets.EC2_PORT }}
#         script: |
#           docker stop skaxis-server || true && docker rm skaxis-server || true
#           docker pull ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest
#           docker run -d --name skaxis-server -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest
#           docker image prune -f
