name: Deploy to EC2
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker images
        run: |
          docker build -t myapp/fastapi:latest ./ai
          docker build -t myapp/springboot:latest ./server/spring
          docker build -t myapp/client:latest ./client
          
          docker push myapp/fastapi:latest
          docker push myapp/springboot:latest
          docker push myapp/client:latest
      
      # EC2에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/SK-AXIS
            docker-compose pull
            docker-compose up -d
