name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # AI 서비스 (FastAPI) 이미지 빌드 및 푸시
    - name: Build and push AI (FastAPI) image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/skaxis-ai:latest ./ai
        docker push ${{ secrets.DOCKER_USERNAME }}/skaxis-ai:latest
    
    # Client 서비스 (Vue.js) 이미지 빌드 및 푸시
    - name: Build and push Client image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/skaxis-client:latest ./client
        docker push ${{ secrets.DOCKER_USERNAME }}/skaxis-client:latest
    
    # Server 서비스 (SpringBoot) 이미지 빌드 및 푸시
    - name: Build and push Server (SpringBoot) image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest ./server/spring
        docker push ${{ secrets.DOCKER_USERNAME }}/skaxis-server:latest
    
    # EC2에 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/SK-AXIS
          docker-compose pull
          docker-compose up -d
