name: Deploy AI Service

on:
  push:
    branches: [ main ]
    paths:
      - 'ai/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ai/**'

jobs:
  build-and-deploy-ai:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push AI image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/skaxis-ai:latest ./ai
        docker push ${{ secrets.DOCKER_USERNAME }}/skaxis-ai:latest
    - name: Deploy AI to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          docker stop skaxis-ai || true && docker rm skaxis-ai || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/skaxis-ai:latest
          docker run -d --name skaxis-ai -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/skaxis-ai:latest
          docker image prune -f